### ISSUE TITLE
小说源

### ISSUE THREAD

**Issue by goudamwdjuyggd** [goudamwdjuyggd/-#5]
[plsw.json](https://github.com/user-attachments/files/16201936/plsw.json)

**Comment by goudamwdjuyggd** [comment]
[qbxs.json](https://github.com/user-attachments/files/16201951/qbxs.json)

**Comment by goudamwdjuyggd** [comment]
[69sb.json](https://github.com/user-attachments/files/16201962/69sb.json)

**Comment by kk9527c** [comment]
用什么打开

**Comment by kk9527c** [comment]
用什么打开> [69sb.json](https://github.com/user-attachments/files/16201962/69sb.json)
>

**Comment by kk9527c** [comment]
> [69sb.json](https://github.com/user-attachments/files/16201962/69sb.json)
> 
用什么打开

**Comment by goudamwdjuyggd** [comment]
[小说10/12更新](https://github.com/user-attachments/files/17349730/xs2.json)
